name: lightsoff
adopt-info: lightsoff
summary: Turn off all the lights
description: |
  Lights Off is a collection of light switch puzzles. Clicking on a light
  toggles it either on or off, but also toggles all the surrounding lights,
  too. Your objective is simple: turn off all the lights!

  Players who delight in turning off lights will enjoy the huge number of
  levels.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core20

# Launchpad doesn't recognize these fields yet
passthrough:
  license: GPL-2.0+
  title: Lights Off

slots:
  # for GtkApplication registration
  lightsoff:
    interface: dbus
    bus: session
    name: org.gnome.LightsOff

apps:
  lightsoff:
    command: usr/bin/lightsoff
    extensions: [gnome-3-38]
    plugs:
      - gsettings
      - opengl
    desktop: usr/share/applications/org.gnome.LightsOff.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas

parts:
# Needed by clutter
  snapcraft-preload:
    source: https://github.com/sergiusens/snapcraft-preload.git
    plugin: cmake
    build-packages:
      - gcc-multilib
      - g++-multilib

  lightsoff:
    source: https://gitlab.gnome.org/GNOME/lightsoff.git
    source-type: git
    source-tag: '40.0.1'
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags --abbrev=10)
    override-build: |
      sed -i.bak -e 's|Icon=org.gnome.LightsOff$|Icon=${SNAP}/meta/gui/org.gnome.LightsOff.svg|g' $SNAPCRAFT_PART_SRC/data/org.gnome.LightsOff.desktop.in
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/scalable/apps/org.gnome.LightsOff.svg $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp $SNAPCRAFT_PART_BUILD/data/org.gnome.LightsOff.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    plugin: meson
    meson-parameters: [--prefix=/snap/lightsoff/current/usr]
    organize:
      snap/lightsoff/current/usr: usr
    build-packages:
      - libclutter-gtk-1.0-dev
      - on amd64:
        - gcc-multilib
        - g++-multilib
